### ISSUE TITLE
Feature request: Option to only export specific tables (filter)?

### ISSUE THREAD

**Issue by nstohler** [kedonec/Korzh.DbUtils#14]
It would be great if I could provide a list with table names and then only those get exported.

**Comment by antifree** [comment]
Hello, thank you for your feature request.
We will think how to implement in in the best way.

**Comment by antifree** [comment]
Hello,
We will publish it tomorrow. 

You will be able to add filter for tables using new command:

```
dbtool filter-tables <your connectionId> <table-list>
```
where `<table-list> -> <table>,<table-list>`

For example:
```
dbtool filter-tables Nwind Orders,OrderDetails
```

**Comment by antifree** [comment]
You can update `dbtool` to version 1.3.0

**Comment by nstohler** [comment]
Thanks for that, I will try it out soon!
