### ISSUE TITLE
NPGSQL return table name in lower case

### ISSUE THREAD

**Issue by silverbulleters-github-service** [kedonec/Korzh.DbUtils#24]
https://github.com/kedonec/Korzh.DbUtils/blob/cf6517d32821292596fb11fa85a4242ee730e6ab/src/Korzh.DbUtils.PostgreSql/PostgreBridge.cs#L192

we have 

> Npgsql.PostgresException: 42P01: relation "SOME" does not exist

because entity-framework create table in `PascalCase`

step to reproduce

1. create table in postgresql database

```
CREATE TABLE public."SomeInCamelCase"
(
    "Id" uuid NOT NULL,
    "Name" text COLLATE pg_catalog."default"
}
```

2. export

```
dbtool connections add development postgre "<ConnectionString>"
dbtool.exe filter-tables development "SomeInCamelCase"
dbtool export development --format=json --output=exporter
```

Another solution - migrate to snake case

* https://stackoverflow.com/questions/35914530/case-insensitive-name-of-tables-and-properties-in-entity-framework-7
* https://andrewlock.net/customising-asp-net-core-identity-ef-core-naming-conventions-for-postgresql/

**Comment by antifree** [comment]
Hello,
What version of Postgre do you use?
What Operating System do you use?

**Comment by antifree** [comment]
It might fix the problem https://github.com/kedonec/Korzh.DbUtils/commit/363d02aab9865d177665e7b22c34d10ce5b005d5

**Comment by silverbulleters-github-service** [comment]
@antifree 

we use for reproduce bug

* Latest stable EntityFramework and latest stable NPGSQL
* ASP.NET 3.x - BlazorServer - development enviroment - Windows 10 Pro
* PosgterSQL 12.1 Alpine in Docker

**Comment by antifree** [comment]
@silverbulleters-github-service 
Hello, 

we have already published [v.1.4.1](https://www.nuget.org/packages/Korzh.DbTool/1.4.1).

**Comment by silverbulleters-github-service** [comment]
Yes - new rellease fix the problem

Thanks, thanks, thanks

![изображение](https://user-images.githubusercontent.com/9207642/76007346-f60e2080-5f1e-11ea-892e-66f1a65b9b78.png)
